// layoutCliente.js

// Layout da entidade "cliente"
module.exports = {
    tip_reg: { inicio: 1, tamanho: 1 },
    cod_siste: { inicio: 2, tamanho: 2 },
    dat_movto: { inicio: 4, tamanho: 8 },
    tip_inter: { inicio: 12, tamanho: 1 },
    cod_credor: { inicio: 13, tamanho: 8 },
    des_regis: { inicio: 21, tamanho: 30 },
    ind_alter: { inicio: 51, tamanho: 1 },
    des_cpf: { inicio: 52, tamanho: 14 },
    nom_clien: { inicio: 66, tamanho: 45 },
    dat_nasci: { inicio: 111, tamanho: 8 },
    nom_conju: { inicio: 119, tamanho: 45 },
    nom_refer: { inicio: 164, tamanho: 45 },
    des_ender_refer: { inicio: 209, tamanho: 50 },
    des_numer_refer: { inicio: 259, tamanho: 10 },
    des_compl_refer: { inicio: 269, tamanho: 50 },
    des_bairr_refer: { inicio: 319, tamanho: 25 },
    des_cidad_refer: { inicio: 344, tamanho: 23 },
    des_estad_refer: { inicio: 367, tamanho: 2 },
    des_cep_refer: { inicio: 369, tamanho: 8 },
    des_fones_refer: { inicio: 377, tamanho: 20 },
    des_obs_refer: { inicio: 397, tamanho: 100 },
    des_filia: { inicio: 497, tamanho: 45 },
    des_ender_resid: { inicio: 542, tamanho: 50 },
    des_numer_resid: { inicio: 592, tamanho: 10 },
    des_compl_resid: { inicio: 602, tamanho: 50 },
    des_bairr_resid: { inicio: 652, tamanho: 25 },
    des_cidad_resid: { inicio: 677, tamanho: 23 },
    des_estad_resid: { inicio: 700, tamanho: 2 },
    des_cep_resid: { inicio: 702, tamanho: 8 },
    des_fones_resid: { inicio: 710, tamanho: 20 },
    nom_empre_comer: { inicio: 730, tamanho: 45 },
    des_setor_comer: { inicio: 775, tamanho: 25 },
    des_cargo_comer: { inicio: 800, tamanho: 30 },
    des_ender_comer: { inicio: 830, tamanho: 50 },
    des_numer_comer: { inicio: 880, tamanho: 10 },
    des_compl_comer: { inicio: 890, tamanho: 50 },
    des_bairr_comer: { inicio: 940, tamanho: 25 },
    des_cidad_comer: { inicio: 965, tamanho: 23 },
    des_estad_comer: { inicio: 988, tamanho: 2 },
    des_cep_comer: { inicio: 990, tamanho: 8 },
    des_fones_comer: { inicio: 998, tamanho: 20 },
    cod_ramal_comer: { inicio: 1018, tamanho: 8 },
    nom_orige: { inicio: 1026, tamanho: 45 },
    dat_refer: { inicio: 1071, tamanho: 8 },
    dat_expir_prazo: { inicio: 1079, tamanho: 8 },
    cod_opera: { inicio: 1087, tamanho: 8 },
    des_dados_compl: { inicio: 1095, tamanho: 255 },
    ind_sexo: { inicio: 1350, tamanho: 1 },
    ind_estad_civil: { inicio: 1351, tamanho: 1 },
    des_rg: { inicio: 1352, tamanho: 10 },
    des_uf_rg: { inicio: 1362, tamanho: 2 },
    dat_cadas_clien: { inicio: 1364, tamanho: 8 },
    cod_profi_clien: { inicio: 1372, tamanho: 8 },
    val_renda: { inicio: 1380, tamanho: 18 },
    dat_admis: { inicio: 1398, tamanho: 8 },
    qtd_oper: { inicio: 1406, tamanho: 4 },
    qtd_renov: { inicio: 1410, tamanho: 4 },
    tip_ender_corre: { inicio: 1414, tamanho: 1 },
    des_fones_celul: { inicio: 1415, tamanho: 20 },
    des_fones1: { inicio: 1435, tamanho: 20 },
    des_fones2: { inicio: 1455, tamanho: 20 },
    des_email: { inicio: 1475, tamanho: 60 },
  };
  